[phases.setup]
nixPkgs = ["python311", "nodejs_18", "pnpm-9_x"]

[phases.install]
cmds = [
    "npm install -g corepack@0.24.1 && corepack enable",
    "pnpm i --frozen-lockfile",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "python app.py"
